defmodule Mud.Repo.Migrations.CreateItemFlags do
  use Ecto.Migration

  def change do
    create table(:item_flags, primary_key: false) do
      add(:id, :binary_id, primary_key: true)
      add(:item_id, references(:items, on_delete: :delete_all, type: :binary_id))

      add(:close, :boolean, default: false)
      add(:coin, :boolean, default: false)
      add(:drop, :boolean, default: false)
      add(:hidden, :boolean, default: false)
      add(:gem, :boolean, default: false)
      add(:gem_pouch, :boolean, default: false)
      add(:hold, :boolean, default: false)
      add(:look, :boolean, default: false)
      add(:open, :boolean, default: false)
      add(:remove, :boolean, default: false)
      add(:stow, :boolean, default: false)
      add(:trash, :boolean, default: false)
      add(:wear, :boolean, default: false)
      add(:armor, :boolean, default: false)
      add(:clothing, :boolean, default: false)
      add(:container, :boolean, default: false)
      add(:furniture, :boolean, default: false)
      add(:instrument, :boolean, default: false)
      add(:jewelry, :boolean, default: false)
      add(:material, :boolean, default: false)
      add(:shield, :boolean, default: false)
      add(:weapon, :boolean, default: false)
      add(:scenery, :boolean, default: false)
      add(:wearable, :boolean, default: false)
    end

    create(index(:item_flags, [:close]))
    create(index(:item_flags, [:coin]))
    create(index(:item_flags, [:drop]))
    create(index(:item_flags, [:gem]))
    create(index(:item_flags, [:gem_pouch]))
    create(index(:item_flags, [:hidden]))
    create(index(:item_flags, [:hold]))
    create(index(:item_flags, [:look]))
    create(index(:item_flags, [:open]))
    create(index(:item_flags, [:remove]))
    create(index(:item_flags, [:stow]))
    create(index(:item_flags, [:trash]))
    create(index(:item_flags, [:wear]))
    create(index(:item_flags, [:armor]))
    create(index(:item_flags, [:clothing]))
    create(index(:item_flags, [:container]))
    create(index(:item_flags, [:furniture]))
    create(index(:item_flags, [:instrument]))
    create(index(:item_flags, [:jewelry]))
    create(index(:item_flags, [:material]))
    create(index(:item_flags, [:shield]))
    create(index(:item_flags, [:weapon]))
    create(index(:item_flags, [:scenery]))
    create(index(:item_flags, [:item_id]))
    create(index(:item_flags, [:wearable]))
  end
end
