version: 0.2

env:
  variables:
    LANG: "en_US.UTF-8"
    LANGUAGE: "en_US:UTF-8"
    LC_ALL: "en_US.UTF-8"
    LC_CTYPE: "en_US.UTF-8"
    HOME: "/root"
    ELIXIR_VERSION: "1.9.1"
    MIX_ENV: "prod"
    PORT: 4000

phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get install -y git
      - DEBIAN_FRONTEND=noninteractive apt-get install -y keyboard-configuration
      - wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && dpkg -i erlang-solutions_2.0_all.deb
      - apt-get update
      - apt-get install -y esl-erlang
      - apt-get install -y elixir
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - mix local.hex --force && mix local.rebar --force && mix hex.info
  build:
    commands:
      - echo Entered the build phase...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd $CODEBUILD_SRC_DIR
      - cd server
      - mix deps.get
      - mix compile
      - echo Building assets
      - cd assets
      - npm install
      - cd ..
      - echo Build started on `date` in dir `pwd`
      - mix phx.digest
      - mix release
      - cp appspec.yml _build/prod/rel/mud/
      - cp -R scripts _build/prod/rel/mud/
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  base-directory: server/_build/prod
  files:
    - "prod-*.tar.gz"
