defmodule Mud.Engine.Adverbs do
  alias Mud.Engine.Adverb
  alias Mud.Engine.Adverb.Type

  def quietly(), do: :quietly
  def quickly(), do: :quickly
  def slowly(), do: :slowly
  def carefully(), do: :carefully
  def swiftly(), do: :swiftly
  def cautiously(), do: :cautiously
  def tenderly(), do: :tenderly
  def lovingly(), do: :lovingly
  def sternly(), do: :sternly
  def giddy(), do: :giddy

  def adverbs(),
    do: [
      %Adverb{
        adverb: "cautiously",
        matchstrings: ["quick", "quickly"],
        raw_input: nil,
        token: quickly(),
        type: Type.manner()
      },
      %Adverb{
        adverb: "slowly",
        matchstrings: ["slow", "slowly"],
        raw_input: nil,
        token: slowly(),
        type: Type.time()
      },
      %Adverb{
        adverb: "carefully",
        matchstrings: ["careful", "carefully"],
        raw_input: nil,
        token: carefully(),
        type: Type.manner()
      },
      %Adverb{
        adverb: "swiftly",
        matchstrings: ["swift", "swiftly"],
        raw_input: nil,
        token: swiftly(),
        type: Type.time()
      },
      %Adverb{
        adverb: "tenderly",
        matchstrings: ["tender", "tenderly"],
        raw_input: nil,
        token: tenderly(),
        type: Type.manner()
      },
      %Adverb{
        adverb: "lovingly",
        matchstrings: ["loving", "lovingly"],
        raw_input: nil,
        token: lovingly(),
        type: Type.manner()
      },
      %Adverb{
        adverb: "sternly",
        matchstrings: ["stern", "sternly"],
        raw_input: nil,
        token: sternly(),
        type: Type.manner()
      },
      %Adverb{
        adverb: "giddy",
        matchstrings: ["giddy", "giddily"],
        raw_input: nil,
        token: cautiously(),
        type: Type.manner()
      }
      # %Adverb{adverb: "about", matchstrings: ["about"], raw_input: nil, token: about(), type: ""},
      # %Adverb{adverb: "above", matchstrings: ["above"], raw_input: nil, token: above(), type: ""},
      # %Adverb{adverb: "according to", matchstrings: ["according to", "accordingto"], raw_input: nil, token: according_to(), type: ""},
      # %Adverb{adverb: "across", matchstrings: ["across"], raw_input: nil, token: across(), type: ""},
      # %Adverb{adverb: "across from", matchstrings: ["across from", "acrossfrom"], raw_input: nil, token: across_from(), type: ""},
      # %Adverb{adverb: "after", matchstrings: ["after", "following"], raw_input: nil, token: following(), type: ""},
      # %Adverb{adverb: "against", matchstrings: ["against"], raw_input: nil, token: against(), type: ""},
      # %Adverb{adverb: "ahead of", matchstrings: ["ahead of", "aheadof"], raw_input: nil, token: ahead_of(), type: ""},
      # %Adverb{adverb: "along", matchstrings: ["along", "along with", "alongwith"], raw_input: nil, token: along(), type: ""},
      # %Adverb{adverb: "amid", matchstrings: ["amid", "amidst"], raw_input: nil, token: amid(), type: ""},
      # %Adverb{adverb: "among", matchstrings: ["among", "amongst"], raw_input: nil, token: among(), type: ""},
      # %Adverb{adverb: "anti", matchstrings: ["anti"], raw_input: nil, token: anti(), type: ""},
      # %Adverb{adverb: "apart from", matchstrings: ["apart from", "apartfrom"], raw_input: nil, token: apart(), type: ""},
      # %Adverb{adverb: "around", matchstrings: ["around"], raw_input: nil, token: around(), type: ""},
      # %Adverb{adverb: "as", matchstrings: ["as"], raw_input: nil, token: as(), type: ""},
      # %Adverb{adverb: "as for", matchstrings: ["as for", "asfor", "as of"], raw_input: nil, token: as_for(), type: ""},
      # %Adverb{adverb: "as of", matchstrings: ["as of", "asof"], raw_input: nil, token: as_of(), type: ""},
      # %Adverb{adverb: "as per", matchstrings: ["as per", "asper"], raw_input: nil, token: as_per(), type: ""},
      # %Adverb{adverb: "as regards", matchstrings: ["as regards", "asregards"], raw_input: nil, token: as_regards(), type: ""},
      # %Adverb{adverb: "as to", matchstrings: ["as to", "asto"], raw_input: nil, token: as_to(), type: ""},
      # %Adverb{adverb: "as well as", matchstrings: ["as well as", "as wellas", "aswell as", "aswellas"], raw_input: nil, token: as_well_as(), type: ""},
      # %Adverb{adverb: "aside from", matchstrings: ["aside from", "asidefrom"], raw_input: nil, token: aside(), type: ""},
      # %Adverb{adverb: "astride", matchstrings: ["astride"], raw_input: nil, token: astride(), type: ""},
      # %Adverb{adverb: "at", matchstrings: ["at"], raw_input: nil, token: at(), type: ""},
      # %Adverb{adverb: "atop", matchstrings: ["atop"], raw_input: nil, token: atop(), type: ""},
      # %Adverb{adverb: "away from", matchstrings: ["away from", "awayfrom"], raw_input: nil, token: away_from(), type: ""},
      # %Adverb{adverb: "back to", matchstrings: ["back to", "backto"], raw_input: nil, token: back_to(), type: ""},
      # %Adverb{adverb: "bar", matchstrings: ["bar", "barring"], raw_input: nil, token: barring(), type: ""},
      # %Adverb{adverb: "based on", matchstrings: ["based on", "basedon"], raw_input: nil, token: based_on(), type: ""},
      # %Adverb{adverb: "because of", matchstrings: ["because of", "becauseof"], raw_input: nil, token: because_of(), type: ""},
      # %Adverb{adverb: "before", matchstrings: ["before"], raw_input: nil, token: before(), type: ""},
      # %Adverb{adverb: "behind", matchstrings: ["behind"], raw_input: nil, token: behind(), type: ""},
      # %Adverb{adverb: "beyond", matchstrings: ["beyond"], raw_input: nil, token: beyond(), type: ""},
      # %Adverb{adverb: "but", matchstrings: ["but"], raw_input: nil, token: but(), type: ""},
      # %Adverb{adverb: "but for", matchstrings: ["but for", "butfor"], raw_input: nil, token: but_for(), type: ""},
      # %Adverb{adverb: "by", matchstrings: ["by"], raw_input: nil, token: by(), type: ""},
      # %Adverb{adverb: "by means of", matchstrings: ["by means of", "by meansof", "bymeans of", "bymeansof", "by using", "by using", "using"], raw_input: nil, token: using(), type: ""},
      # %Adverb{adverb: "circa", matchstrings: ["circa"], raw_input: nil, token: circa(), type: ""},
      # %Adverb{adverb: "concerning", matchstrings: ["concerning"], raw_input: nil, token: concerning(), type: ""},
      # %Adverb{adverb: "considering", matchstrings: ["considering"], raw_input: nil, token: considering(), type: ""},
      # %Adverb{adverb: "contrary to", matchstrings: ["contrary to", "contraryto"], raw_input: nil, token: contrary_to(), type: ""},
      # %Adverb{adverb: "counter to", matchstrings: ["counter to", "counterto"], raw_input: nil, token: counter_to(), type: ""},
      # %Adverb{adverb: "counting", matchstrings: ["counting"], raw_input: nil, token: counting(), type: ""},
      # %Adverb{adverb: "depending on", matchstrings: ["dependingon", "depending on"], raw_input: nil, token: depending_on(), type: ""},
      # %Adverb{adverb: "down", matchstrings: ["down"], raw_input: nil, token: down(), type: ""},
      # %Adverb{adverb: "due to", matchstrings: ["dueto", "due to"], raw_input: nil, token: due_to(), type: ""},
      # %Adverb{adverb: "during", matchstrings: ["during"], raw_input: nil, token: during(), type: ""},
      # %Adverb{adverb: "excluding", matchstrings: ["excluding", "excepting", "exceptfor", "except for", "except"], raw_input: nil, token: except(), type: ""},
      # %Adverb{adverb: "far from", matchstrings: ["farfrom", "far from"], raw_input: nil, token: far_from(), type: ""},
      # %Adverb{adverb: "for", matchstrings: ["for"], raw_input: nil, token: forr(), type: ""},
      # %Adverb{adverb: "forwards of", matchstrings: ["forwardsof", "forwards of", "forwardof", "forward of"], raw_input: nil, token: forward_of(), type: ""},
      # %Adverb{adverb: "from", matchstrings: ["from"], raw_input: nil, token: from(), type: ""},
      # %Adverb{adverb: "further to", matchstrings: ["furtherto", "further to"], raw_input: nil, token: further_to(), type: ""},
      # %Adverb{adverb: "given", matchstrings: ["given"], raw_input: nil, token: given(), type: ""},
      # %Adverb{adverb: "in addition to", matchstrings: ["inadditionto", "inaddition to", "in additionto", "in addition to"], raw_input: nil, token: in_addition_to(), type: ""},
      # %Adverb{adverb: "in between", matchstrings: ["inbetween", "in between", "between"], raw_input: nil, token: between(), type: ""},
      # %Adverb{adverb: "in case of", matchstrings: ["incaseof", "incase of", "in caseof", "in case of"], raw_input: nil, token: in_case_of(), type: ""},
      # %Adverb{adverb: "in front of", matchstrings: ["infrontof", "infront of", "in frontof", "in front of"], raw_input: nil, token: in_front_of(), type: ""},
      # %Adverb{adverb: "in spite of", matchstrings: ["inspiteof", "inspite of", "in spiteof", "in spite of", "despite"], raw_input: nil, token: despite(), type: ""},
      # %Adverb{adverb: "in view of", matchstrings: ["inviewof", "inview of", "in viewof", "in view of"], raw_input: nil, token: in_view_of(), type: ""},
      # %Adverb{adverb: "including", matchstrings: ["including"], raw_input: nil, token: including(), type: ""},
      # %Adverb{adverb: "inside", matchstrings: ["inside", "in"], raw_input: nil, token: inside(), type: ""},
      # %Adverb{adverb: "instead of", matchstrings: ["insteadof", "instead of"], raw_input: nil, token: instead_of(), type: ""},
      # %Adverb{adverb: "left of", matchstrings: ["leftof", "left of"], raw_input: nil, token: left_of(), type: ""},
      # %Adverb{adverb: "less", matchstrings: ["less"], raw_input: nil, token: less(), type: ""},
      # %Adverb{adverb: "like", matchstrings: ["like"], raw_input: nil, token: like(), type: ""},
      # %Adverb{adverb: "minus", matchstrings: ["minus"], raw_input: nil, token: minus(), type: ""},
      # %Adverb{adverb: "near to", matchstrings: ["nearto", "near to", "near", "close to", "closeto"], raw_input: nil, token: near(), type: ""},
      # %Adverb{adverb: "next to", matchstrings: ["nextto", "next to", "beside", "besides", "alongside", "adjacent to", "adjacentto"], raw_input: nil, token: beside(), type: ""},
      # %Adverb{adverb: "of", matchstrings: ["of"], raw_input: nil, token: of(), type: ""},
      # %Adverb{adverb: "off", matchstrings: ["off"], raw_input: nil, token: off(), type: ""},
      # %Adverb{adverb: "on", matchstrings: ["on"], raw_input: nil, token: on(), type: ""},
      # %Adverb{adverb: "on account of", matchstrings: ["onaccountof", "onaccount of", "on accountof", "on account of"], raw_input: nil, token: on_account_of(), type: ""},
      # %Adverb{adverb: "on behalf of", matchstrings: ["onbehalfof", "onbehalf of", "on behalfof", "on behalf of"], raw_input: nil, token: on_behalf_of(), type: ""},
      # %Adverb{adverb: "on board", matchstrings: ["onboard", "on board"], raw_input: nil, token: on_board(), type: ""},
      # %Adverb{adverb: "on to", matchstrings: ["on to"], raw_input: nil, token: on_to(), type: ""},
      # %Adverb{adverb: "on to", matchstrings: ["onto"], raw_input: nil, token: onto(), type: ""},
      # %Adverb{adverb: "on top of", matchstrings: ["ontopof", "ontop of", "on topof", "on top of"], raw_input: nil, token: on_top_of(), type: ""},
      # %Adverb{adverb: "opposite to", matchstrings: ["oppositeto", "opposite to", "oppositeof", "opposite of", "opposite"], raw_input: nil, token: opposite(), type: ""},
      # %Adverb{adverb: "other than", matchstrings: ["otherthan", "other than"], raw_input: nil, token: other_than(), type: ""},
      # %Adverb{adverb: "out from", matchstrings: ["outfrom", "out from"], raw_input: nil, token: out_from(), type: ""},
      # %Adverb{adverb: "out of", matchstrings: ["outof", "out of"], raw_input: nil, token: out_of(), type: ""},
      # %Adverb{adverb: "outside of", matchstrings: ["outsideof", "outside of", "outside"], raw_input: nil, token: outside(), type: ""},
      # %Adverb{adverb: "over", matchstrings: ["over"], raw_input: nil, token: over(), type: ""},
      # %Adverb{adverb: "owing to", matchstrings: ["owingto", "owing to"], raw_input: nil, token: owing_to(), type: ""},
      # %Adverb{adverb: "past", matchstrings: ["past"], raw_input: nil, token: past(), type: ""},
      # %Adverb{adverb: "pending", matchstrings: ["pending"], raw_input: nil, token: pending(), type: ""},
      # %Adverb{adverb: "plus", matchstrings: ["plus"], raw_input: nil, token: plus(), type: ""},
      # %Adverb{adverb: "prior to", matchstrings: ["priorto", "prior to"], raw_input: nil, token: prior_to(), type: ""},
      # %Adverb{adverb: "pro", matchstrings: ["pro", "infavorof", "infavor of", "in favorof", "in favor of"], raw_input: nil, token: pro(), type: ""},
      # %Adverb{adverb: "rather than", matchstrings: ["ratherthan", "rather than", "inlieuof", "inlieu of", "in lieuof", "in lieu of"], raw_input: nil, token: instead(), type: ""},
      # %Adverb{adverb: "regarding", matchstrings: ["regarding"], raw_input: nil, token: regarding(), type: ""},
      # %Adverb{adverb: "regardless of", matchstrings: ["regardlessof", "regardless of"], raw_input: nil, token: regardless_of(), type: ""},
      # %Adverb{adverb: "respecting", matchstrings: ["respecting"], raw_input: nil, token: respecting(), type: ""},
      # %Adverb{adverb: "right of", matchstrings: ["rightof", "right of"], raw_input: nil, token: right_of(), type: ""},
      # %Adverb{adverb: "round", matchstrings: ["round"], raw_input: nil, token: round(), type: ""},
      # %Adverb{adverb: "save", matchstrings: ["save"], raw_input: nil, token: save(), type: ""},
      # %Adverb{adverb: "save for", matchstrings: ["savefor", "save for"], raw_input: nil, token: save_for(), type: ""},
      # %Adverb{adverb: "saving", matchstrings: ["saving"], raw_input: nil, token: saving(), type: ""},
      # %Adverb{adverb: "since", matchstrings: ["since"], raw_input: nil, token: since(), type: ""},
      # %Adverb{adverb: "subsequent to", matchstrings: ["subsequentto", "subsequent to"], raw_input: nil, token: subsequent_to(), type: ""},
      # %Adverb{adverb: "such as", matchstrings: ["suchas", "such as"], raw_input: nil, token: such_as(), type: ""},
      # %Adverb{adverb: "than", matchstrings: ["than"], raw_input: nil, token: than(), type: ""},
      # %Adverb{adverb: "thanks to", matchstrings: ["thanksto", "thanks to"], raw_input: nil, token: thanks_to(), type: ""},
      # %Adverb{adverb: "through", matchstrings: ["through"], raw_input: nil, token: through(), type: ""},
      # %Adverb{adverb: "throughout", matchstrings: ["throughout"], raw_input: nil, token: throughout(), type: ""},
      # %Adverb{adverb: "thru", matchstrings: ["thru"], raw_input: nil, token: thru(), type: ""},
      # %Adverb{adverb: "till", matchstrings: ["till"], raw_input: nil, token: till(), type: ""},
      # %Adverb{adverb: "to", matchstrings: ["to"], raw_input: nil, token: to(), type: ""},
      # %Adverb{adverb: "together with", matchstrings: ["togetherwith", "together with"], raw_input: nil, token: together_with(), type: ""},
      # %Adverb{adverb: "touching", matchstrings: ["touching"], raw_input: nil, token: touching(), type: ""},
      # %Adverb{adverb: "towards", matchstrings: ["towards"], raw_input: nil, token: towards(), type: ""},
      # %Adverb{adverb: "underneath", matchstrings: ["underneath", "under", "below", "beneath"], raw_input: nil, token: beneath(), type: ""},
      # %Adverb{adverb: "unlike", matchstrings: ["unlike"], raw_input: nil, token: unlike(), type: ""},
      # %Adverb{adverb: "until", matchstrings: ["until"], raw_input: nil, token: until(), type: ""},
      # %Adverb{adverb: "up", matchstrings: ["up"], raw_input: nil, token: up(), type: ""},
      # %Adverb{adverb: "upagainst", matchstrings: ["upagainst", "up against"], raw_input: nil, token: up_against(), type: ""},
      # %Adverb{adverb: "upon", matchstrings: ["upon"], raw_input: nil, token: upon(), type: ""},
      # %Adverb{adverb: "upto", matchstrings: ["upto", "up to"], raw_input: nil, token: up_to(), type: ""},
      # %Adverb{adverb: "upuntil", matchstrings: ["upuntil", "up until"], raw_input: nil, token: up_until(), type: ""},
      # %Adverb{adverb: "versus", matchstrings: ["versus"], raw_input: nil, token: versus(), type: ""},
      # %Adverb{adverb: "via", matchstrings: ["via"], raw_input: nil, token: via(), type: ""},
      # %Adverb{adverb: "using", matchstrings: ["using", "with"], raw_input: nil, token: using(), type: ""},
      # %Adverb{adverb: "with reference to", matchstrings: ["withreferenceto", "withreference to", "with referenceto", "with reference to"], raw_input: nil, token: with_reference_to(), type: ""},
      # %Adverb{adverb: "with regard to", matchstrings: ["withregardsto", "withregards to", "with regardsto", "with regards to", "withregardto", "withregard to", "with regardto", "with regard to"], raw_input: nil, token: with_regard_to(), type: ""},
      # %Adverb{adverb: "within", matchstrings: ["within", "into", "insideof", "inside of", "inside", "in"], raw_input: nil, token: inside(), type: ""},
      # %Adverb{adverb: "without", matchstrings: ["without"], raw_input: nil, token: without(), type: ""},
      # %Adverb{adverb: "worth", matchstrings: ["worth"], raw_input: nil, token: worth(), type: ""},
    ]
end
