version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/mud
hooks:
  BeforeInstall:
    - location: CodeDeploySetupEnvironmentVariables.sh
  AfterInstall:
    - location: CodeDeployUnzipRelease.sh
  ApplicationStart:
    - location: CodeDeployStartRelease.sh
