version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/mud
hooks:
  # AfterInstall:
  #   - location: CodeDeployUnzipRelease.sh
  ApplicationStart:
    - location: scripts/start.sh
