version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/mud
hooks:
  BeforeInstall:
    - location: _build/prod/scripts/start.sh
  ApplicationStart:
    - location: _build/prod/scripts/start.sh
