defmodule MudWeb.Views.Character.Settings.ColorsView do
  use MudWeb, :view

  def render("colors.json", %{colors: colors}) do
    %{
      id: colors.id,
      system_info: colors.system_info,
      system_warning: colors.system_warning,
      system_alert: colors.system_alert,
      area_name: colors.area_name,
      area_description: colors.area_description,
      character: colors.character,
      exit: colors.exit,
      denizen: colors.denizen,
      denizen_label: colors.denizen_label,
      on_ground_label: colors.on_ground_label,
      toi_label: colors.toi_label,
      exit_label: colors.exit_label,
      character_label: colors.character_label,
      base: colors.base,
      echo: colors.echo,
      furniture: colors.furniture,
      equipment: colors.equipment,
      weapon: colors.weapon,
      armor: colors.armor,
      gem: colors.gem,
      coin: colors.coin,
      ammunition: colors.ammunition,
      shield: colors.shield,
      clothing: colors.clothing,
      structure: colors.structure,
      jewelry: colors.jewelry,
      misc: colors.misc,
      portal: colors.portal,
      closable: colors.closable,
      direction: colors.direction,
      object: colors.object,
      input: colors.input,
      input_background: colors.input_background,
      input_button_background: colors.input_button_background,
      input_button_icon: colors.input_button_icon,
      story_background: colors.story_background,
      story_history_icon: colors.story_history_icon,
      story_history_border: colors.story_history_border,
      window_toolbar_background: colors.window_toolbar_background,
      window_toolbar_label: colors.window_toolbar_label,
      window_lock_unlocked: colors.window_lock_unlocked,
      window_lock_locked: colors.window_lock_locked,
      window_move_unlocked: colors.window_move_unlocked,
      window_move_locked: colors.window_move_locked
    }
  end
end
