defmodule Mud.Repo.Migrations.CreateItemFlags do
  use Ecto.Migration

  def change do
    create table(:item_flags, primary_key: false) do
      add(:id, :binary_id, primary_key: true)
      add(:item_id, references(:items, on_delete: :delete_all, type: :binary_id))

      add(:close, :boolean, default: false)
      add(:drop, :boolean, default: false)
      add(:hidden, :boolean, default: false)
      add(:hold, :boolean, default: false)
      add(:look, :boolean, default: false)
      add(:open, :boolean, default: false)
      add(:remove, :boolean, default: false)
      add(:stow, :boolean, default: false)
      add(:trash, :boolean, default: false)
      add(:wear, :boolean, default: false)
      add(:is_armor, :boolean, default: false)
      add(:is_clothing, :boolean, default: false)
      add(:is_coin, :boolean, default: false)
      add(:is_equipment, :boolean, default: false)
      add(:is_furniture, :boolean, default: false)
      add(:is_gem, :boolean, default: false)
      add(:is_gem_pouch, :boolean, default: false)
      add(:is_jewelry, :boolean, default: false)
      add(:is_material, :boolean, default: false)
      add(:is_instrument, :boolean, default: false)
      add(:is_shield, :boolean, default: false)
      add(:is_weapon, :boolean, default: false)
      add(:is_scenery, :boolean, default: false)
      add(:is_structure, :boolean, default: false)
      add(:is_wearable, :boolean, default: false)
      add(:is_misc, :boolean, default: false)
      add(:is_shop_display, :boolean, default: false)
    end

    create(index(:item_flags, [:close]))
    create(index(:item_flags, [:drop]))
    create(index(:item_flags, [:hidden]))
    create(index(:item_flags, [:hold]))
    create(index(:item_flags, [:look]))
    create(index(:item_flags, [:open]))
    create(index(:item_flags, [:remove]))
    create(index(:item_flags, [:stow]))
    create(index(:item_flags, [:trash]))
    create(index(:item_flags, [:wear]))
    create(index(:item_flags, [:is_armor]))
    create(index(:item_flags, [:is_clothing]))
    create(index(:item_flags, [:is_coin]))
    create(index(:item_flags, [:is_equipment]))
    create(index(:item_flags, [:is_furniture]))
    create(index(:item_flags, [:is_gem]))
    create(index(:item_flags, [:is_gem_pouch]))
    create(index(:item_flags, [:is_instrument]))
    create(index(:item_flags, [:is_jewelry]))
    create(index(:item_flags, [:is_material]))
    create(index(:item_flags, [:is_scenery]))
    create(index(:item_flags, [:is_shield]))
    create(index(:item_flags, [:is_weapon]))
    create(index(:item_flags, [:item_id]))
    create(index(:item_flags, [:is_wearable]))
    create(index(:item_flags, [:is_structure]))
    create(index(:item_flags, [:is_misc]))
    create(index(:item_flags, [:is_shop_display]))
  end
end
