{application,ecto_autoslug_field,
             [{applications,[kernel,stdlib,elixir,logger,ecto,slugger]},
              {description,"Autoslug field for Ecto."},
              {modules,['Elixir.EctoAutoslugField',
                        'Elixir.EctoAutoslugField.Slug',
                        'Elixir.EctoAutoslugField.SlugBase',
                        'Elixir.EctoAutoslugField.SlugGenerator',
                        'Elixir.EctoAutoslugField.Type']},
              {registered,[]},
              {vsn,"2.0.1"}]}.
